chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
    crochat,
    sentMessages,
    receivedMessages,
    chatNotification,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('friend/<str:pk>/', create_or_return_private_chat, name='create_or_return_private_chat'),
    path('friendlist/', crochat, name= 'crochat'),
    path('sent_msg/<str:pk>/', sentMessages, name = 'sent_msg'),
    path('rec_msg/<str:pk>/', receivedMessages, name = 'rec_msg'),
    path('notification/', chatNotification, name = 'notification'),



]

social/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
    like_post,
    like_video,
    upload,
    delete_post,
    delete_video,
    video_post,
    follow,
    account_view,
    profile,
    comment_post,
    comment_vid,
)

from personal.views import (
	home_screen_view,
    front_view,
)

from videochat.views import (
    room,
    getToken,
    createMember,
    getMember,
    deleteMember,
)


urlpatterns = [
    path('', home_screen_view, name='home'),
    path('welcome/', front_view, name='frontpart'),
    path('account/', include('account.urls', namespace='account')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('videochat/', include('videochat.urls', namespace='videochat')),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('room/', room, name="roommie"),
    path('get_token/', getToken, name="getToken"),

    path('create_member/', createMember, name="createMember"),
    path('get_member/', getMember, name="getMember"),
    path('delete_member/', deleteMember, name="deleteMember"),
    path('search/', account_search_view, name="search"),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
    path('profile/<str:pk>', profile, name='profile'),
    path('<user_id>/', account_view, name="view"),
    path('like-post', like_post, name='like-post'),
    path('like-video', like_video, name='like-video'),
    path('comment_post', comment_post, name='comment_post'),
    path('comment_vid', comment_vid, name='comment_vid'),
    path('upload', upload, name='upload'),
    path('delete_post', delete_post, name='delete_post'),
    path('delete_video', delete_video, name='delete_video'),
    path('video_post', video_post, name='video_post'),
    path('follow', follow, name='follow'),
    


    
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

chat/forms.py
from django import forms
from django.forms import CharField, ModelForm
from chat.models import ChatMessage


class ChatMessageForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={"class":"forms", "rows":3, "placeholder": "Type message here"}))
    class Meta:
        model = ChatMessage
        fields = ["body", "image", "video", "file"]
        
    def save(self, commit=True):
        message = super(ChatMessageForm, self).save(commit=False)
        message.body = self.cleaned_data['body']
        message.video = self.cleaned_data['video']
        message.image = self.cleaned_data['image']
        message.file = self.cleaned_data['file']
        if commit:
            message.save()
        return message


	

chat/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.conf import settings
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.utils import timezone
from urllib.parse import urlencode
import json
import base64
from itertools import chain
from datetime import datetime
import pytz
from django.http import JsonResponse
from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage
from django.core import files
import os


from chat.forms import ChatMessageForm
from friend.models import FriendList
from account.models import Account
from chat.models import PrivateChatRoom, RoomChatMessage, ChatMessage
from chat.utils import find_or_create_private_chat




DEBUG = False
TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"



def private_chat_room_view(request, *args, **kwargs):
    room_id = request.GET.get("room_id")
    user = request.user
    if not user.is_authenticated:
        base_url = reverse('login')
        query_string = urlencode({'next': f"/chat/?room_id={room_id}"})
        url = f"{base_url}?{query_string}"
        return redirect(url)
    
    context = {}
    context['m_and_f'] = get_recent_chatroom_messages(user)
    context["BASE_URL"] = settings.BASE_URL
    if room_id:
        context["room_id"] = room_id
        context['debug'] = DEBUG
        context['debug_mode'] = settings.DEBUG
    return render(request, "chat/room.html", context)

        
def get_recent_chatroom_messages(user):
	"""
	sort in terms of most recent chats (users that you most recently had conversations with)
	"""
	# 1. Find all the rooms this user is a part of 
	rooms1 = PrivateChatRoom.objects.filter(user1=user, is_active=True)
	rooms2 = PrivateChatRoom.objects.filter(user2=user, is_active=True)

	# 2. merge the lists
	rooms = list(chain(rooms1, rooms2))

	# 3. find the newest msg in each room
	m_and_f = []
	for room in rooms:
		# Figure out which user is the "other user" (aka friend)
		if room.user1 == user:
			friend = room.user2
		else:
			friend = room.user1

		# confirm you are even friends (in case chat is left active somehow)
		friend_list = FriendList.objects.get(user=user)
		if not friend_list.is_mutual_friend(friend):
			chat = find_or_create_private_chat(user, friend)
			chat.is_active = False
			chat.save()
		else:	
			# find newest msg from that friend in the chat room
			try:
				message = RoomChatMessage.objects.filter(room=room, user=friend).latest("timestamp")
			except RoomChatMessage.DoesNotExist:
				# create a dummy message with dummy timestamp
				today = datetime(
					year=1950, 
					month=1, 
					day=1, 
					hour=1,
					minute=1,
					second=1,
					tzinfo=pytz.UTC
				)
				message = RoomChatMessage(
					user=friend,
					room=room,
					timestamp=today,
					content="",
				)
			m_and_f.append({
				'message': message,
				'friend': friend
			})

	return sorted(m_and_f, key=lambda x: x['message'].timestamp, reverse=True)


# Ajax call to return a private chatroom or create one if does not exist

def create_or_return_private_chat(request,pk):
    friend = FriendList.objects.get(user_id=pk)
    user = request.user
    profile = Account.objects.get(pk=friend.user.id)
    payload = {}
    form = ChatMessageForm()
    chats = ChatMessage.objects.all()
    rec_chats = ChatMessage.objects.filter(msg_sender=profile, msg_receiver=user, seen=False)
    rec_chats.update(seen=True)
    if user.is_authenticated:
        if request.method == "POST":
            form = ChatMessageForm(request.POST, request.FILES, instance=request.user)
            chat = find_or_create_private_chat(profile, user)
            if form.is_valid():
                try: 
                    chat_message = form.save(commit=False)
                    chat_message.msg_sender = user
                    chat_message.msg_receiver = profile
                    chat_message.save()
                    print("Successfully got the chat")
                    payload['response'] = "Successfully got the chat."
                    payload['chatroom_id'] = chat.id
                    return redirect("create-or-return-private-chat", pk=friend.profile.id)
                except Account.DoesNotExist:
                    payload['response'] = "Unable to start a chat with that user."
        
        context = {
			"friend": friend, "form": form, "user":user, 
            "profile":profile, "chats": chats, "num": rec_chats.count()
		}
        return render(request, "chat/room.html", context)

    
    else:
        payload['response'] = "You can't start a chat if you are not authenticated."
        return HttpResponse(json.dumps(payload), content_type="application/json")

def crochat(request):
    user = request.user
    profile = Account.objects.get(pk=user.id)
    friend_list = FriendList.objects.get(user=profile)
    friend_list.save()
    friends = friend_list.friends.all()
    context = {"user": user, "friends": friends}
    return render(request, "chat/snippets/create_or_return_private_chat.html", context)


def sentMessages(request, pk):
    user = request.user
    friend = FriendList.objects.get(user_id=pk)
    profile = Account.objects.get(pk=friend.user.id)
    data = json.loads(request.body)
    new_chat = data["msg"]
    new_chat_message = ChatMessage.objects.create(body=new_chat, msg_sender=user, msg_receiver=profile, seen=False )
    print(new_chat)
    return JsonResponse(new_chat_message.body, safe=False)

def receivedMessages(request, pk):
    user = request.user
    friend = FriendList.objects.get(user_id=pk)
    profile = Account.objects.get(pk=friend.user.id)
    arr = []
    chats = ChatMessage.objects.filter(msg_sender=profile, msg_receiver=user)
    for chat in chats:
        arr.append(chat.body)
    return JsonResponse(arr, safe=False)

def chatNotification(request):
    user = request.user
    friends = user.friends.all()
    arr = []
    for friend in friends:
        chats = ChatMessage.objects.filter(msg_sender__id=friend.user.id, msg_receiver=user, seen=False)
        arr.append(chats.count())
    return JsonResponse(arr, safe=False)
    
def save_temp_profile_image_from_base64String(imageString, user):
    INCORRECT_PADDING_EXCEPTION = "Incorrect padding"
    ACCESS = 'chat/room.html'
    try:
        url = os.path.join(ACCESS + "/" + str(user.pk))
        storage = FileSystemStorage(location=url)
        image = base64.b64decode(imageString)
        with storage.open('', 'wb+') as destination:
            destination.write(image)
            destination.close()
        return url
    except Exception as e:
        print("exception: " + str(e))
		# workaround for an issue I found
        if str(e) == INCORRECT_PADDING_EXCEPTION:
            imageString += "=" * ((4 - len(imageString) % 4) % 4)
            return save_temp_profile_image_from_base64String(imageString, user)
    return None


    
  






    

chat/templates/chat/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chatty</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link rel="stylesheet" href="{% static 'css/emojionearea.min.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/11.0.1/markdown-it.min.js" integrity="sha512-hW0KbtvDnXCHbh2UCNP/6R+oXxCKiOfm9ciuUekdGBCQF1+57bGqZAk3sAFir7PMQstyRW0UecsSc2HQotH2vg==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/default.min.css" integrity="sha512-kZqGbhf9JTB4bVJ0G8HCkqmaPcRgo88F0dneK30yku5Y/dep7CZfCnNml2Je/sY4lBoqoksXz4PtVXS4GHSUzQ==" crossorigin="anonymous" />
    <script src="{% static 'js/emojionearea.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'vendor/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-migrate-1.4.1.js' %}"></script>

   <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
</head>
<body>

    {% block content %}
    <h1>Hello world</h1>
    {% endblock %}
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

chat/templates/chat/room.html
{% extends "chat/base.html" %}
{% load static %}

{% block content %}
<style>
    
    .prst{
        color: #fff;
        background: grey;
        border: 2px solid rgb(243, 14, 148);
        border-radius: 50%;
        text-align: center;
        font-size: 11px;
        height: 10px;
        width: 10px;
        position: absolute;
        box-sizing: content-box;
        font-weight: 600;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: -10px;
      }
    .forms{
        border: 1px solid slateblue;
        
        width: 100%;
        border-radius: 5px;
        padding: 10px 10px;
        font-size: 18px;
    }

    .emi {
        width: 50px;
        height: 50px;
    }
    
    .btn1 {
        transform: translateX(-50%);
        transition: all 200ms;  
        cursor: pointer;
        margin-left: 100px;
        
    }
    
</style>

<div class="chat-container2">
    <div class="identity">
        <div>
           <a href="{% url 'chat:crochat' %}">
            <svg
            xmlns="http://www.w3.org/2000/svg"
            width="26"
            height="26"
            fill="currentColor"
            class="bi bi-house"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"
            />
            <path
              fill-rule="evenodd"
              d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"
            />
          </svg>
           </a>
        </div>

        <h3>{{friend.user.username}}</h3>
        <span></span>

        <div class="pro-pic">
            <img src="{{friend.user.profile_image.url}}" alt="profile-picture">                
            {% if friend.user.is_authenticated %}
              <div class="prst" id="presence"></div> 
            {% else %}
             <div class="prst" ></div> 
            {% endif %}
        </div>


    </div>

    <div class="sub-container">


        <div class="chat-body" id="chat-body">

            
            {% for chat in chats %}
            {% if chat.msg_sender == user and chat.msg_receiver == profile %}

            <div class="chat-box-sent">
                {{chat}}
            </div>

            


            {% elif chat.msg_sender == profile and chat.msg_receiver == user %}

            <div class="chat-box-received">
                {{chat}}
            </div>
        

            {% endif %}


            {% endfor %}


        

            <div class="chat-box-sent" id ="chat-box-sent" style="display: none">
               
            </div>

            
        </div>
    
        <form action="" id="myform" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            {{form.body}}

            <span class="dropdown" style="cursor: pointer;">
                <span class="dropdown-toggle" data-toggle="dropdown" class="d-flex">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera-fill" viewBox="0 0 16 16">
                        <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                        <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera-reels" viewBox="0 0 16 16">
                        <path d="M6 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM1 3a2 2 0 1 0 4 0 2 2 0 0 0-4 0z"/>
                        <path d="M9 6h.5a2 2 0 0 1 1.983 1.738l3.11-1.382A1 1 0 0 1 16 7.269v7.462a1 1 0 0 1-1.406.913l-3.111-1.382A2 2 0 0 1 9.5 16H2a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h7zm6 8.73V7.27l-3.5 1.555v4.35l3.5 1.556zM1 8v6a1 1 0 0 0 1 1h7.5a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1z"/>
                        <path d="M9 6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM7 3a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-mic-fill" viewBox="0 0 16 16">
                        <path d="M5 3a3 3 0 0 1 6 0v5a3 3 0 0 1-6 0V3z"/>
                        <path d="M3.5 6.5A.5.5 0 0 1 4 7v1a4 4 0 0 0 8 0V7a.5.5 0 0 1 1 0v1a5 5 0 0 1-4.5 4.975V15h3a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1h3v-2.025A5 5 0 0 1 3 8V7a.5.5 0 0 1 .5-.5z"/>
                      </svg>
                </span>
                <div class="dropdown-menu">
                    <a href="#" class="dropdown-item" onclick="ChooseImage()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera-fill" viewBox="0 0 16 16">
                            <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                            <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
                          </svg>
                          <input type="file" id="imageFile" onchange="SendImage(this)" accept="image/*" style="display: none;" name="image"/>
                        </a>
                       <a href="#" class="dropdown-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera-reels" viewBox="0 0 16 16">
                            <path d="M6 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM1 3a2 2 0 1 0 4 0 2 2 0 0 0-4 0z"/>
                            <path d="M9 6h.5a2 2 0 0 1 1.983 1.738l3.11-1.382A1 1 0 0 1 16 7.269v7.462a1 1 0 0 1-1.406.913l-3.111-1.382A2 2 0 0 1 9.5 16H2a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h7zm6 8.73V7.27l-3.5 1.555v4.35l3.5 1.556zM1 8v6a1 1 0 0 0 1 1h7.5a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1z"/>
                            <path d="M9 6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM7 3a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                          </svg>
                          <input type="file" id="videoFile" accept="video/*" />
                        </a>
                    <a href="#" class="dropdown-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-mic-fill" viewBox="0 0 16 16">
                            <path d="M5 3a3 3 0 0 1 6 0v5a3 3 0 0 1-6 0V3z"/>
                            <path d="M3.5 6.5A.5.5 0 0 1 4 7v1a4 4 0 0 0 8 0V7a.5.5 0 0 1 1 0v1a5 5 0 0 1-4.5 4.975V15h3a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1h3v-2.025A5 5 0 0 1 3 8V7a.5.5 0 0 1 .5-.5z"/>
                          </svg>
                        </a>
                
            
                </div>
                
            </span>
            <button type = "submit" id = "submit">
                <span class="material-icons">send
                </span>           
             </button>
        </form>

        
        
           
        <button class="btn1">
            <img src="{% static 'icons/Untitled design (4).gif' %}" class="emi" alt="">
        </button>

    </div>

</div>

<script src="{% static 'js/Emoji.js' %}"></script>



<script type="text/javascript">

    var imageFile;
	var base64ImageString;

    new EmojiPicker({
        trigger: [
            {
                insertInto: ['.forms'],
                selector: '.btn1'
            }
        ],
        closeButton: true,
        dragButton: true
    });
    

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');

    let form = document.getElementById("myform")
    
    form.addEventListener("submit", sendChat)

    function sendChat(e){
        e.preventDefault()
        let chatMessage= document.getElementById("id_body").value
        console.log(chatMessage)
        

        const data = { msg: chatMessage };
        
        let url = "{% url 'chat:sent_msg' friend.user.id %}"

fetch(url, {
  method: 'POST', // or 'PUT'
  headers: {
    'Content-Type': 'application/json',
    'X-CSRFToken': csrftoken
  },
  body: JSON.stringify(data),
})
.then(response => response.json())
.then(data => {
  console.log('Success:', data);
  let chat_body = document.getElementById('chat-body')
  let chatMessageBox = document.createElement("div")
  chatMessageBox.classList.add("chat-box-sent")
  chatMessageBox.innerText = data
  chat_body.append(chatMessageBox)
  document.getElementById("id_body").value=""
})
.catch((error) => {
  console.error('Error:', error);
});


    }





setInterval(receiveMessages, 2000)


let counter = {{num}}
function receiveMessages(){


    let url = "{% url 'chat:rec_msg' friend.user.id %}"

        fetch(url)
        .then(response => response.json())
        .then(data => {
        console.log('Success:', data);
        
        

        if(data.length == 0){}

        else{

            let lastMsg = data[data.length-1]

            if(counter == data.length){
                console.log("there is no new chat")
            }

        
        

            else{


                let chat_body = document.getElementById('chat-body')
                let chatMessageBox = document.createElement("div") 
                chatMessageBox.classList.add("chat-box-received")
                chatMessageBox.innerText = lastMsg
                chat_body.append(chatMessageBox)
                document.getElementById("id_body").value=""
                console.log()

                console.log


            }

        }
        
        counter = data.length



        })
        .catch((error) => {
        console.error('Error:', error);
        });

}

function ChooseImage() {
    document.getElementById('imageFile').click();
}  

/* return null if invalid or base64String if valid */
function isImageSizeValid(image){
    console.log("max size: {{DATA_UPLOAD_MAX_MEMORY_SIZE}}")
    // console.log(image)
    var startIndex = image.indexOf("base64,") + 7;
    var base64str = image.substr(startIndex);
    var decoded = atob(base64str);
    console.log("FileSize: " + decoded.length);
    if(decoded.length>= "{{DATA_UPLOAD_MAX_MEMORY_SIZE}}"){
        return null
    }
    return base64str
}

function SendImage(event) {
    let chatImage = document.get
    var file = event.files[0];

    if (!file.type.match("image.*")) {
        alert("Please select image only");
    }
    else {
        var reader = new FileReader();

        reader.addEventListener('load', function() {
            let chat_body = document.getElementById('chat-body')
            var image = reader.result
            var imageField = document.getElementById('chat-box-sent')
            imageField.src = image
            chat_body.append(imageField)
            document.getElementById("chat-body").value="";
            document.getElementById("chat-body").focus();

            
        }, false);

        if (file) {
            reader.readAsDataURL(file);
        }
    }
}

function hasNetwork(online) {
    const element = document.querySelector("span");
    const element1 = document.getElementById("presence");
    // Update the DOM to reflect the current status
    if (online) {
      element1.style.backgroundColor = 'green'
      element.innerText = "Online";
    } else {
      element1.style.backgroundColor = 'grey'
      element.innerText = "Offline";
    }
  }
   
  window.addEventListener("load", () => {
    hasNetwork(navigator.onLine);
    window.addEventListener("online", () => {
      // Set hasNetwork to online when they change to online.
      hasNetwork(true);
    });
    window.addEventListener("offline", () => {
      // Set hasNetwork to offline when they change to offline.
      hasNetwork(false);
    });
  });
  
  




</script>


{% endblock %}